# preload = /home/aske/nix-config/dotfiles/hypr/wallpapers/1365871.jpg
# wallpaper = *, /home/aske/nix-config/dotfiles/hypr/wallpapers/1365871.jpg
wallpaper {
    monitor =
    path = /home/aske/nix-config/dotfiles/hypr/wallpapers/petani.jpg
		fit_mode = cover
}
