# WORK MONITOR
# echo $(hyprctl monitors | grep "ID 1" | awk '{print $2}' | tr -d ':')

# If at work use these settings:
$workMonitor = DP-1 
monitor=$workMonitor,2560x1080@60.000,0x0,1
# THINKPAD MONITOR
monitor=eDP-1,3840x2160@60.000,2560x0,2

# If at home use these settings:
# $samsungMonitor = DVI-I-1
# monitor = $samsungMonitor, 1920x1080@60.000,0x0,1
# # THINKPAD MONITOR
# monitor=eDP-1,3840x2160@60.000,1920x0,2
